### ISSUE TITLE
expose setting to change user-agent

### ISSUE THREAD

**Issue by jgpeak** [Stebon24/redwrap#11]
Hey, one of the requirements of using the reddit API is custom user agents. Can you expose a setting to configure that within your package?

Reddit API Resource: https://github.com/reddit/reddit/wiki/API

First Paragraph, second bullet point.

**Comment by pitaj** [comment]
Working on it now :smile: 

I've taken over maintenance of this repo

**Comment by pitaj** [comment]
Fixed with commit 0694968b2fcebcc1b5460144fc7ab1dc4ddec7fb
